#!/usr/local/bin/php -q
<?php

require_once 'vendor/autoload.php';
Twig_Autoloader::register();

error_reporting(E_ALL);

$loader = new Twig_Loader_Filesystem('templates');
$twig = new Twig_Environment($loader, array(
    'debug' => true,
));
$twig->addExtension(new Twig_Extension_Escaper(false));


$installPath=$argv[1];
$appName=$argv[2];
$xml=$argv[3];

function createDirectoryLayout($installPath=null, $appName=null){

	if(empty($appName)) trigger_error("App name must be entered", E_USER_ERROR);

	if(!file_exists($installPath))
		trigger_error("Directory $installPath must exist.", E_USER_ERROR);

	if(!is_writable(($installPath)) )
		trigger_error( "$installPath must be writable.", E_USER_ERROR);

	$handle = fopen("dir_layout", "r");
	
	if(!$handle)
		trigger_error("Can't find directory layout schema", E_USER_ERROR);

	mkdir($installPath . DIRECTORY_SEPARATOR . $appName);

	$lastPath = "";
	while(!feof($handle)){
		$dir = fgets($handle);

		if(empty($lastPath))
			$lastPath = trim($dir);

		if(substr_count($dir, "\t") > 0){
			$dirLevels = substr_count($dir, "\t");
			$pathLevels = substr_count($lastPath, DIRECTORY_SEPARATOR);
			
			if($dirLevels > $pathLevels){
				$lastPath .= DIRECTORY_SEPARATOR . trim($dir);
			} elseif($dirLevels < $pathLevels){
				$lastPath = substr($lastPath, 0, strrpos($lastPath, DIRECTORY_SEPARATOR) );
				$lastPath = substr($lastPath, 0, strrpos($lastPath, DIRECTORY_SEPARATOR) ) . DIRECTORY_SEPARATOR . trim($dir);
			} else {
				$lastPath = substr($lastPath, 0, strrpos($lastPath, DIRECTORY_SEPARATOR) );
				$lastPath .= DIRECTORY_SEPARATOR . trim($dir);
			}
		} else{
			$lastPath = trim($dir);
		}

		if(empty($lastPath))
			return;
		
		
		$newDirectory = $installPath . DIRECTORY_SEPARATOR . $appName . DIRECTORY_SEPARATOR . $lastPath;
		$dirWasCreatead = mkdir($newDirectory);
		
		if($dirWasCreatead)
			echo "mkdir $newDirectory ... OK" . PHP_EOL;
		else {
			echo "mkdir $newDirectory ... FAIL" . PHP_EOL;
			die;
		}
	}
}

function dal($xml, $twig, $installPath, $appName) {
	libxml_use_internal_errors ( true );
	
	$doc = new \DOMDocument ();
	$doc->loadHTML( $xml);
	$xp = new \DOMXPath ( $doc );
	$classes = $xp->query("//fuderal/class");

	//var_dump($xp->query("var", $constants[0])[0]->nodeValue);
	//var_dump($attributes[0]);
	foreach($classes as $c){
		$className 		= $c->getAttribute('name');
		$parentClass 	= $c->getAttribute('extends');
		$parentNamespace= $c->getAttribute('parent_namespace');
		$parentAlias 	= $c->getAttribute('parent_alias');
		$classVisibility= $c->getAttribute('visibility');
		$namespace 		= $c->getAttribute('namespace');

		
		$classOrmMapping=function() use($xp, $c) {
			$nodeList = $xp->query("orm", $c);
			$ret = [];
			foreach ($nodeList as $node) {
				$annotation = $node->nodeValue;
				if(empty($annotation)) continue;
				$o = [
					"annotation" => $annotation
				];
				array_push($ret, $o);
			}
			return $ret;
		};

		$constants=function() use($xp, $c) {
			$nodeList = $xp->query("const", $c);
			$ret = [];
			foreach ($nodeList as $node) {
				$o = [
					"group" => $node->getAttribute('group'),
					"varname" => [],
					"value" => [],
					"label" => []
				];
				foreach ($xp->query("varname", $node) as $el) {
					array_push($o['varname'], $el->nodeValue);
				}				
				foreach ($xp->query("value", $node) as $el) {
					array_push($o['value'], $el->nodeValue);
				}
				foreach ($xp->query("label", $node) as $el) {
					array_push($o['label'], $el->nodeValue);
				}
				array_push($ret, $o);
			}
			return $ret;
		};

		$interfaces=function() use($xp, $c) {
			$nodeList = $xp->query("implements", $c);
			$ret = [];
			foreach ($nodeList as $node) {
				$className = $node->nodeValue;
				if(empty($className)) continue;
				$o = [
					"fqcn" => $node->getAttribute('namespace') ."\\". $className ,
					"alias" => $node->getAttribute('alias') ,
					"classname" => $className
				];
				array_push($ret, $o);
			}
			return $ret;
		};

		$classProperties=function() use($xp, $c) {
			$nodeList = $xp->query("attribute", $c);
			$ret = [];
			foreach ($nodeList as $node) {
				$className = $node->nodeValue;
				if(empty($className)) continue;
				$static = $xp->query("static", $node)[0];
				$initNode = $node->getElementsByTagName("init");
				$o = [
					"visibility" => $node->getElementsByTagName("visibility")[0]->nodeValue ,
					"static" => empty($static) || strcmp($static->nodeValue, "static") != 0 ? "" : "static" ,
					"orm" =>  $node->getElementsByTagName("orm")[0]->nodeValue,
					"type" => $node->getElementsByTagName("type")[0]->nodeValue ,
					"name" => $node->getElementsByTagName("varname")[0]->nodeValue,
					"init" => ($initNode->length === 0)? null : $initNode[0]->nodeValue
				];
				array_push($ret, $o);
			}
			return $ret;
		};

		$methods=function() use($xp, $c) {
			$nodeList = $xp->query("method", $c);
			$ret = [];
			foreach ($nodeList as $node) {
				$className = $node->nodeValue;
				$static = $xp->query("static", $node)[0];
				$parameters=[];

				foreach ($node->getElementsByTagName("parameter") as $param) {
					array_push($parameters, [
						"type" => $param->getElementsByTagName('type')[0]->nodeValue,
						"name" => $param->getElementsByTagName('name')[0]->nodeValue
					]);
				}

				if(empty($className)) continue;
				$o = [
					"visibility" => $node->getElementsByTagName("visibility")[0]->nodeValue ,
					"static" => empty($static) || strcmp($static->nodeValue, "static") != 0 ? "" : "static" ,
					"orm" =>  $node->getElementsByTagName("orm")[0]->nodeValue,
					"functionName" => $node->getElementsByTagName("function")[0]->nodeValue ,
					"body" => $node->getElementsByTagName("code")[0]->nodeValue,
					"parameters" => $parameters
				];
				array_push($ret, $o);
			}
			return $ret;
		};

		$constructorBody=function() use($classProperties){
			$ret = [];
			foreach ($classProperties() as $prop) {
				if(!empty($prop['orm']) && (strcmp($prop['type'], "array") == 0 || !empty(strstr($prop['type'], "[]")) ) ){
					array_push($ret, 
						"\$this->".$prop['name']." = new Doctrine\Common\Collections\ArrayCollection()");
				}
			}
			return $ret;
		};


		$source = $twig->render('class.php', 
			[
				"license" => "Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) \n* https://creativecommons.org/licenses/by-sa/4.0/legalcode",
				"namespace" => "$namespace",
				"docs" => [
					"author" => "marcelbonnet@anatel.gov.br",
					"date" => (new DateTime())->format("Y-m-d"),
					"since" => "1.0-SNAPSHOT"
				],
				"class_orm" => $classOrmMapping(),
				"class_name" => "$className",
				"class_visibility" => "$classVisibility",
				"extending_class" => [
					[ "fqcn" => "$parentNamespace\\$parentClass", "alias" => "$parentAlias", "classname" => "$parentClass" ]
				],
				"implementing_interfaces" => $interfaces(),
				"constructor_parameters" => [ 
					/*
					["classname" => "", "name" => ""],
					["classname" => "", "name" => ""],
					*/
				],
				"constructorBody" => $constructorBody(),
				//================================
				"class_constants" => $constants(),
				"class_properties" => $classProperties(),
				"methods" => $methods(),
			]
		);

		file_put_contents($installPath . DIRECTORY_SEPARATOR . $appName . DIRECTORY_SEPARATOR . "app". DIRECTORY_SEPARATOR ."src". DIRECTORY_SEPARATOR ."dao". DIRECTORY_SEPARATOR . $className .".php" , $source );

	}//classes
}

createDirectoryLayout($installPath, $appName);
dal(file_get_contents($xml,'r'), $twig, $installPath, $appName);

exit;
/*
//$template = $twig->load('constructor.twig'); //Twig_TemplateWrapper
//$template->render( [ ]);

echo $twig->render('class.php', 
	[
		"license" => "Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) \n* https://creativecommons.org/licenses/by-sa/4.0/legalcode",
		"namespace" => "MyNamespace",
		"docs" => [
			"author" => "marcelbonnet@anatel.gov.br",
			"date" => (new DateTime())->format("Y-m-d"),
			"since" => "1.0-RELEASE"
		],
		"class_name" => "MyClass",
		"class_modifier" => "abstract",
		"extending_class" => [
			[ "fqcn" => "My\Namespace\MyParentClass", "classname" => "MyParentClass" ]
		],
		"implementing_interfaces" => [
			["fqcn" => "SlimCloud\Core\cmd\AbstractCommand", "classname" => "AbstractCommand"],
			["fqcn" => "SlimCloud\Core\cmd\HomeCommand", "classname" => "HomeCommand"],
		],
		"constructor_parameters" => [ 
			["classname" => "AcaoFiscalizacao", "name" => "acaoFiscalizacao"],
			["classname" => "AgenteFiscalizacao", "name" => "agenteFiscalizacao"],
		],
		//================================
		"class_properties" => [
			["visibility" => "public", "is_const" => false, "is_static" => true, "name" => "name", "type" => "string" ],
			["visibility" => "protected", "is_const" => false, "is_static" => false, "name" => "surname", "type" => "string" ],
			["visibility" => "private", "is_const" => false, "is_static" => false, "name" => "birth", "type" => "\DateTime" ],
		],
	]
);
*/